networks:
  default:
    external: true
    name: finance-master-service

services:
  librarydb:
    image: mariadb:10.11
    #    image: mariadb
    volumes:
      - ./migrations/library-data.sql:/docker-entrypoint-initdb.d/library-data.sql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APPLICATION_USER}
      MYSQL_PASSWORD: ${DB_APPLICATION_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3310:3306"
    networks:
      - default

    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${DB_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      timeout: 2s
      retries: 10

#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${DB_ROOT_PASSWORD}" ]
#      interval: 5s
#      retries: 10
#      start_period: 10s

  libraryportal:
    build:
      context: .
    image: library_portal:latest
    ports:
      - "8082:8082"

    environment:
      spring.datasource.url: jdbc:mariadb://librarydb:3306/${DB_NAME}
      spring.datasource.username: ${DB_APPLICATION_USER}
      spring.datasource.password: ${DB_APPLICATION_PASSWORD}
      spring.jpa.database-platform: org.hibernate.dialect.MariaDBDialect


    depends_on:
      librarydb:
        condition: service_healthy

    networks:
      - default



